const posts = [
    {
        "title": "Историята на механичните часовници",
        "date": "4 февруари 2025",
        "image": "OMEGA-Watches-Hero-Banner.jpg",
        "snippet": "Механичните часовници са истинско чудо на инженерната мисъл.",
        "content": "<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3><br>\n\nDuis ut magna magna. In mauris sapien, ultricies sit amet leo eu, pharetra gravida ante. Mauris egestas sodales commodo. Nulla at risus eget dolor aliquam condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris lobortis tortor rutrum hendrerit viverra. Proin id porttitor diam, ut interdum nisl. Vivamus vitae lectus elementum, sagittis leo a, aliquet elit. Mauris sollicitudin pellentesque tellus sit amet laoreet. Donec quis neque vitae quam euismod aliquam. Aliquam pharetra faucibus suscipit.\n\n<br><br><br><h3>Mauris vehicula est odio.</h3><br>\n\nPellentesque aliquam rutrum laoreet. In dignissim elit a justo facilisis malesuada. Sed porttitor mattis aliquet. Suspendisse potenti. Nunc pharetra feugiat felis, et aliquam nulla lobortis a. Fusce scelerisque orci at velit convallis, id accumsan diam commodo. Sed a quam vel libero ullamcorper bibendum. Donec ut mattis nisi. Mauris gravida auctor quam nec pretium. Nam eleifend ex vitae mauris lobortis elementum.\n\n<br><br><br><h3>Duis nec sagittis urna.</h3><br>\n\nInteger sollicitudin malesuada tortor eu pulvinar. Praesent mattis arcu ut dolor iaculis, posuere egestas velit viverra. Mauris faucibus risus quis nibh ornare tincidunt. Donec venenatis at velit a lobortis. In ullamcorper maximus posuere. Quisque ut malesuada quam.\n\n<br><br><br><h3>Aliquam a lectus facilisis elit dapibus dapibus in eu purus.</h3><br>\n\nOrci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Mauris ac est id nisi facilisis aliquet. Fusce tortor dui, gravida nec urna et, cursus euismod massa. Nullam id ultrices mi. Vestibulum dapibus, odio a congue commodo, erat mi malesuada tellus, eget lacinia arcu ex eget sapien. Phasellus dictum facilisis odio, sed vulputate ex viverra a. Praesent vel nisi volutpat, condimentum lorem quis, mattis urna. Suspendisse potenti. Cras non consequat elit, sit amet laoreet orci. Donec vel congue tortor. Sed vitae lacus quis enim feugiat vulputate in tristique nulla. Donec a augue porta, faucibus diam id, sodales nulla. Suspendisse quis neque libero.\n\n<br><br><br><h3>Ut pretium, lorem auctor vehicula rhoncus, dui lacus suscipit lacus, at bibendum risus dui ut orci.</h3><br>\n\nInteger velit odio, interdum eget turpis vitae, finibus ultrices lectus. Proin gravida laoreet pulvinar. Etiam nec viverra ex, ut hendrerit nulla. Integer posuere ligula ultrices tortor sollicitudin, vel auctor dolor aliquet. Sed pretium ante commodo ultricies dignissim. Duis pharetra, tortor sed lacinia viverra, lorem velit ullamcorper risus, interdum ultrices neque turpis quis augue. Aenean non lacus id urna fermentum faucibus sit amet nec leo. Maecenas elit ligula, mollis sit amet fermentum non, tincidunt quis nisi. Sed a massa arcu. Integer et dolor ut velit fringilla commodo. Nullam sed ipsum rutrum, commodo velit vel, vulputate mi.",
        "slug": "историята-на-механичните-часовници"
    },
    {
        "title": "Как да поддържаме водоустойчивите часовници",
        "date": "31 януари 2025",
        "image": "EJ_HEro Banner 3840x1212pxBuyersGuide.jpg",
        "snippet": "Водоустойчивостта на часовниците е важна характеристика.",
        "content": "<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3><br>\n\nDuis ut magna magna. In mauris sapien, ultricies sit amet leo eu, pharetra gravida ante. Mauris egestas sodales commodo. Nulla at risus eget dolor aliquam condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris lobortis tortor rutrum hendrerit viverra. Proin id porttitor diam, ut interdum nisl. Vivamus vitae lectus elementum, sagittis leo a, aliquet elit. Mauris sollicitudin pellentesque tellus sit amet laoreet. Donec quis neque vitae quam euismod aliquam. Aliquam pharetra faucibus suscipit.\n\n<br><br><br><h3>Mauris vehicula est odio.</h3><br>\n\nPellentesque aliquam rutrum laoreet. In dignissim elit a justo facilisis malesuada. Sed porttitor mattis aliquet. Suspendisse potenti. Nunc pharetra feugiat felis, et aliquam nulla lobortis a. Fusce scelerisque orci at velit convallis, id accumsan diam commodo. Sed a quam vel libero ullamcorper bibendum. Donec ut mattis nisi. Mauris gravida auctor quam nec pretium. Nam eleifend ex vitae mauris lobortis elementum.\n\n<br><br><br><h3>Duis nec sagittis urna.</h3><br>\n\nInteger sollicitudin malesuada tortor eu pulvinar. Praesent mattis arcu ut dolor iaculis, posuere egestas velit viverra. Mauris faucibus risus quis nibh ornare tincidunt. Donec venenatis at velit a lobortis. In ullamcorper maximus posuere. Quisque ut malesuada quam.\n\n<br><br><br><h3>Aliquam a lectus facilisis elit dapibus dapibus in eu purus.</h3><br>\n\nOrci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Mauris ac est id nisi facilisis aliquet. Fusce tortor dui, gravida nec urna et, cursus euismod massa. Nullam id ultrices mi. Vestibulum dapibus, odio a congue commodo, erat mi malesuada tellus, eget lacinia arcu ex eget sapien. Phasellus dictum facilisis odio, sed vulputate ex viverra a. Praesent vel nisi volutpat, condimentum lorem quis, mattis urna. Suspendisse potenti. Cras non consequat elit, sit amet laoreet orci. Donec vel congue tortor. Sed vitae lacus quis enim feugiat vulputate in tristique nulla. Donec a augue porta, faucibus diam id, sodales nulla. Suspendisse quis neque libero.\n\n<br><br><br><h3>Ut pretium, lorem auctor vehicula rhoncus, dui lacus suscipit lacus, at bibendum risus dui ut orci.</h3><br>\n\nInteger velit odio, interdum eget turpis vitae, finibus ultrices lectus. Proin gravida laoreet pulvinar. Etiam nec viverra ex, ut hendrerit nulla. Integer posuere ligula ultrices tortor sollicitudin, vel auctor dolor aliquet. Sed pretium ante commodo ultricies dignissim. Duis pharetra, tortor sed lacinia viverra, lorem velit ullamcorper risus, interdum ultrices neque turpis quis augue. Aenean non lacus id urna fermentum faucibus sit amet nec leo. Maecenas elit ligula, mollis sit amet fermentum non, tincidunt quis nisi. Sed a massa arcu. Integer et dolor ut velit fringilla commodo. Nullam sed ipsum rutrum, commodo velit vel, vulputate mi.",
        "slug": "как-да-поддържаме-водоустойчивите-часовници"
    },
    {
        "title": "Модни тенденции за 2025",
        "date": "28 януари 2025",
        "image": "hero-contact-banner.jpg",
        "snippet": "Новите модни тенденции в света на часовниците за 2025.",
        "content": "<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3><br>\n\nDuis ut magna magna. In mauris sapien, ultricies sit amet leo eu, pharetra gravida ante. Mauris egestas sodales commodo. Nulla at risus eget dolor aliquam condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris lobortis tortor rutrum hendrerit viverra. Proin id porttitor diam, ut interdum nisl. Vivamus vitae lectus elementum, sagittis leo a, aliquet elit. Mauris sollicitudin pellentesque tellus sit amet laoreet. Donec quis neque vitae quam euismod aliquam. Aliquam pharetra faucibus suscipit.\n\n<br><br><br><h3>Mauris vehicula est odio.</h3><br>\n\nPellentesque aliquam rutrum laoreet. In dignissim elit a justo facilisis malesuada. Sed porttitor mattis aliquet. Suspendisse potenti. Nunc pharetra feugiat felis, et aliquam nulla lobortis a. Fusce scelerisque orci at velit convallis, id accumsan diam commodo. Sed a quam vel libero ullamcorper bibendum. Donec ut mattis nisi. Mauris gravida auctor quam nec pretium. Nam eleifend ex vitae mauris lobortis elementum.\n\n<br><br><br><h3>Duis nec sagittis urna.</h3><br>\n\nInteger sollicitudin malesuada tortor eu pulvinar. Praesent mattis arcu ut dolor iaculis, posuere egestas velit viverra. Mauris faucibus risus quis nibh ornare tincidunt. Donec venenatis at velit a lobortis. In ullamcorper maximus posuere. Quisque ut malesuada quam.\n\n<br><br><br><h3>Aliquam a lectus facilisis elit dapibus dapibus in eu purus.</h3><br>\n\nOrci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Mauris ac est id nisi facilisis aliquet. Fusce tortor dui, gravida nec urna et, cursus euismod massa. Nullam id ultrices mi. Vestibulum dapibus, odio a congue commodo, erat mi malesuada tellus, eget lacinia arcu ex eget sapien. Phasellus dictum facilisis odio, sed vulputate ex viverra a. Praesent vel nisi volutpat, condimentum lorem quis, mattis urna. Suspendisse potenti. Cras non consequat elit, sit amet laoreet orci. Donec vel congue tortor. Sed vitae lacus quis enim feugiat vulputate in tristique nulla. Donec a augue porta, faucibus diam id, sodales nulla. Suspendisse quis neque libero.\n\n<br><br><br><h3>Ut pretium, lorem auctor vehicula rhoncus, dui lacus suscipit lacus, at bibendum risus dui ut orci.</h3><br>\n\nInteger velit odio, interdum eget turpis vitae, finibus ultrices lectus. Proin gravida laoreet pulvinar. Etiam nec viverra ex, ut hendrerit nulla. Integer posuere ligula ultrices tortor sollicitudin, vel auctor dolor aliquet. Sed pretium ante commodo ultricies dignissim. Duis pharetra, tortor sed lacinia viverra, lorem velit ullamcorper risus, interdum ultrices neque turpis quis augue. Aenean non lacus id urna fermentum faucibus sit amet nec leo. Maecenas elit ligula, mollis sit amet fermentum non, tincidunt quis nisi. Sed a massa arcu. Integer et dolor ut velit fringilla commodo. Nullam sed ipsum rutrum, commodo velit vel, vulputate mi.",
        "slug": "модни-тенденции-за-2025"
    }
];